name: Publish to NPM

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    branches: ['main']
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install pnpm
          uses: pnpm/action-setup@v2
          with:
              version: latest
        - name: Set up Node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'pnpm'
        - name: Install dependencies
          run: pnpm install
        - name: Build
          run: pnpm build
        - name: NPM publish
          uses: JS-DevTools/npm-publish@v2
          with:
            token: ${{ secrets.NPM_TOKEN }}